version: "3"
services:
    database:
        image: postgres:11.2-alpine
        container_name: database
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: sail
            POSTGRES_DB: crud
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    crud-laravel-hml:
        working_dir: /app
        image: webdevops/php-apache-dev:8.0
        container_name: crud-laravel
        build:
            context: .
        ports:
            - "8080:80"
        volumes:
            - ".:/app"
        restart: always
        environment:
            ANBIENT: 2
            PHP_DATE_TIMEZONE: America/Maceio
